"""The Polar adapter (app/billing/providers/polar.py, specs/010 T029b): what the shared contract suite cannot say about it.

tests/billing/test_provider_contract.py holds every adapter to the same promises. This file is what is particular to Polar's wire
formats: its Standard Webhooks signature and the two keys a secret can mean, its Order and event shapes, and a Checkout API that has no
idempotency, so a retry is made safe by looking before creating. Hermetic: the signing is computed in-process and the HTTP is
`httpx.MockTransport`.

## Why the tests do not just agree with the code

  * The signature vectors were generated by the **Standard Webhooks library** and every one of them was verified under **Polar's own SDK**
    (`polar.webhooks._verify_signature`, polar-sdk 1.0.2) at the instants used here, in a throwaway environment outside this repository's
    dependencies. The SDK is also the oracle for the window: it accepts exactly T-300 and T+300 and refuses T-301 and T+301.
  * The payload fixtures in tests/billing/fixtures/polar_*.json were generated by **`polar trigger <event> --json --seed 7`**, Polar's own
    tooling building a payload from its own schema, so the adapter is shown real Order shapes (every field, the buyer's name, address and
    email included), not only dicts shaped by this file's author. The sample buyer is the generator's fiction. `--seed 7` gives every
    fixture the same order id, so a purchase and its refund really do share one.
"""
import base64
import hashlib
import hmac
import json
from pathlib import Path

import httpx
import pytest

from app.billing import providers
from app.billing.providers.base import (
    BillingCustomer,
    Capability,
    CheckoutError,
    CreditProduct,
    EventKind,
    InvalidPayload,
    InvalidSignature,
)
from app.billing.providers.polar import ATTEMPT_KEY, PolarProvider, _signing_keys
from tests.billing.fake_polar_api import FakePolarApi

FIXTURES = Path(__file__).parent / "fixtures"
T = 1_760_000_000
# --- generated by the Standard Webhooks library, verified under Polar's own SDK ------------------------------------------------------
NEW_SECRET = "whsec_cG9sYXIta25vd24tYW5zd2VyLWtleSEh"  # Standard Webhooks: the base64 remainder is the key
LEGACY_SECRET = "polar_known_answer_legacy_32chr"  # Polar HMAC (secrets before 2026-09-08): the UTF-8 bytes are the key
OTHER_SECRET = "whsec_c29tZS1vdGhlci1lbmRwb2ludHMta2V5IQ=="
KNOWN_BODY = b'{"type":"order.refunded","timestamp":"2026-10-08T14:10:11.209162Z","api_version":"2026-10","data":{"id":"ord_ka_1"}}'
MSG_ID = "msg_known_answer_1"
NEW_SIG = "v1,8SN2lDsiC4IpVDZ37Tt+tBzyaIWMiNBWe8LtyxMCr2M="
LEGACY_SIG = "v1,NgiZfUxjbB3JKVu1bGzrzHeBXTXcbiRXYLUK5ljG6MQ="
OLD_SIG = "v1,p5KIRknczIE7RATeOOJg0e3lrKE5zl+lvqTrlOSMYG4="  # a rolled-out secret's signature, first in a rolled header


def provider(secret: str = NEW_SECRET, now: float = T + 10, **kwargs) -> PolarProvider:
    kwargs.setdefault("access_token", "polar_oat_x")
    kwargs.setdefault("environment", "sandbox")
    return PolarProvider(secret, clock=lambda: now, **kwargs)


def headers(signature: str = NEW_SIG, *, event_id: str = MSG_ID, stamp: str = str(T)) -> dict[str, str]:
    return {"webhook-id": event_id, "webhook-timestamp": stamp, "webhook-signature": signature}


def parse(p: PolarProvider, hdrs: dict[str, str], body: bytes = KNOWN_BODY):
    return p.parse_webhook(hdrs, body)


def sign(body: bytes, *, event_id: str = MSG_ID, stamp: int = T, secret: str = NEW_SECRET) -> dict[str, str]:
    """Sign `body` the documented way with the new-scheme key, so only the mapping is under test."""
    key = base64.b64decode(secret.removeprefix("whsec_"))
    mac = base64.b64encode(hmac.new(key, f"{event_id}.{stamp}.".encode() + body, hashlib.sha256).digest()).decode()
    return headers(f"v1,{mac}", event_id=event_id, stamp=str(stamp))


class TestTheSignature:
    def test_a_header_generated_for_a_new_style_secret_is_accepted(self):
        (event,) = parse(provider(), headers(NEW_SIG))

        assert event.event_id == MSG_ID and event.raw_type == "order.refunded"

    def test_a_header_generated_for_a_legacy_secret_is_accepted_because_both_keys_are_tried(self):
        """A secret does not say whether it was made before or after 2026-09-08, so the key it means is whichever one verifies."""
        assert parse(provider(LEGACY_SECRET), headers(LEGACY_SIG))

    def test_a_rolled_header_with_an_old_signature_and_an_unknown_version_in_front_is_accepted_because_any_v1_may_match(self):
        assert parse(provider(), headers(f"{OLD_SIG} v2,AAAA {NEW_SIG}"))

    def test_a_signature_made_with_the_other_style_of_key_does_not_cross_secrets(self):
        with pytest.raises(InvalidSignature):
            parse(provider(LEGACY_SECRET), headers(NEW_SIG))

    def test_another_endpoints_secret_is_refused(self):
        with pytest.raises(InvalidSignature):
            parse(provider(OTHER_SECRET), headers(NEW_SIG))

    def test_a_version_other_than_v1_is_never_enough_even_for_an_arithmetically_right_signature(self):
        right_mac = NEW_SIG.split(",", 1)[1]

        for label in ("v2", "v0", "v1a", ""):
            with pytest.raises(InvalidSignature):
                parse(provider(), headers(f"{label},{right_mac}"))

    @pytest.mark.parametrize("missing", ["webhook-id", "webhook-timestamp", "webhook-signature"])
    def test_a_missing_header_is_refused(self, missing):
        hdrs = headers()
        del hdrs[missing]

        with pytest.raises(InvalidSignature):
            parse(provider(), hdrs)

    @pytest.mark.parametrize("stamp", ["", "abc", "nan", "inf", "-inf", "1e999", "0x10"])
    def test_a_malformed_timestamp_is_refused_not_a_crash(self, stamp):
        with pytest.raises(InvalidSignature):
            parse(provider(), headers(stamp=stamp))

    @pytest.mark.parametrize("signature", ["", "garbage", "v1,", "v1,!!!not-base64!!!", "v1,AAAA", ",,,", "v1", "  "])
    def test_a_malformed_signature_is_refused_not_a_crash(self, signature):
        with pytest.raises(InvalidSignature):
            parse(provider(), headers(signature))

    def test_the_window_is_symmetric_and_inclusive_exactly_as_polars_own_verifier_is(self):
        """Unlike Stripe's, Polar's verifier refuses a timestamp in the FUTURE too: the SDK accepts T-300 and T+300 and refuses T-301 and T+301."""
        for edge in (T + 300, T - 300):
            assert parse(provider(now=edge), headers())
        for beyond in (T + 301, T - 301):
            with pytest.raises(InvalidSignature):
                parse(provider(now=beyond), headers())

    def test_the_event_id_is_bound_into_the_mac_so_a_delivery_cannot_be_replayed_as_another_event(self):
        with pytest.raises(InvalidSignature):
            parse(provider(), headers(event_id="msg_someone_elses"))

    def test_the_timestamp_is_bound_into_the_mac_so_it_cannot_be_moved_to_make_an_old_delivery_look_fresh(self):
        with pytest.raises(InvalidSignature):
            parse(provider(now=T + 400), headers(stamp=str(T + 100)))

    def test_a_body_altered_after_signing_is_refused(self):
        with pytest.raises(InvalidSignature):
            parse(provider(), headers(), KNOWN_BODY.replace(b"ord_ka_1", b"ord_ka_2"))

    def test_header_names_are_case_insensitive(self):
        upper = {k.upper(): v for k, v in headers().items()}

        assert parse(provider(), upper)

    def test_a_tolerance_of_zero_is_refused_because_it_disables_the_check(self):
        with pytest.raises(ValueError, match="tolerance"):
            PolarProvider(NEW_SECRET, tolerance_seconds=0)

    def test_a_provider_with_no_secret_cannot_exist(self):
        with pytest.raises(ValueError, match="secret"):
            PolarProvider("")


class TestWhichKeysASecretCanMean:
    def test_a_whsec_secret_means_its_own_bytes_and_its_decoded_base64_remainder(self):
        assert _signing_keys(NEW_SECRET) == (NEW_SECRET.encode(), b"polar-known-answer-key!!")

    def test_a_secret_that_is_not_base64_means_only_its_own_bytes(self):
        assert _signing_keys("not base64 at all !!!") == (b"not base64 at all !!!",)

    def test_a_secret_that_decodes_to_itself_is_not_listed_twice(self):
        assert len(set(_signing_keys("whsec_"))) == len(_signing_keys("whsec_"))

    def test_the_32_character_secret_the_polar_cli_printed_in_the_sandbox_verifies_under_its_raw_bytes(self):
        """That secret had no `whsec_` prefix and was valid base64 by accident; the raw key is the one that matched Polar's signature."""
        secret = "AbCdEfGhIjKlMnOpQrStUvWxYz012345"
        body = b'{"type":"order.paid","data":{}}'
        mac = base64.b64encode(hmac.new(secret.encode(), f"{MSG_ID}.{T}.".encode() + body, hashlib.sha256).digest()).decode()

        assert parse(provider(secret), headers(f"v1,{mac}"), body)


def fixture(name: str) -> bytes:
    return (FIXTURES / f"polar_{name}.json").read_bytes()


def deliver(body: bytes | dict | list | str, *, event_id: str = "msg_1", p: PolarProvider | None = None):
    raw = body if isinstance(body, bytes) else json.dumps(body).encode()
    return (p or provider(now=T)).parse_webhook(sign(raw, event_id=event_id), raw)


def order(**overrides) -> dict:
    data = {
        "id": "ord_1", "status": "paid", "paid": True, "billing_reason": "purchase", "customer_id": "cus_1", "product_id": "prod_1",
        "total_amount": 1000, "net_amount": 900, "tax_amount": 100, "refunded_amount": 0, "currency": "usd",
    }
    return {"type": "order.paid", "timestamp": "2026-10-08T14:10:11.209162Z", "api_version": "2026-10", "data": {**data, **overrides}}


class TestRealSchemaPayloads:
    """The fixtures are Polar's own generator's output, full Orders with every field."""

    def test_a_real_purchase_is_a_purchase_with_every_reference_the_app_needs(self):
        raw = fixture("order_paid_purchase")
        data = json.loads(raw)["data"]

        (event,) = deliver(raw, event_id="msg_real_1")

        assert event.kind is EventKind.CREDITS_PURCHASED and event.event_id == "msg_real_1"
        assert (event.customer_ref, event.product_ref, event.payment_ref) == (data["customer_id"], data["product_id"], data["id"])
        assert (event.amount_minor, event.currency, event.raw_type) == (data["total_amount"], data["currency"], "order.paid")
        assert event.occurred_at is not None and event.occurred_at.tzinfo is not None

    def test_a_real_subscription_order_grants_nothing(self):
        (event,) = deliver(fixture("order_paid_subscription"))

        assert event.kind is EventKind.IGNORED
        assert (event.customer_ref, event.product_ref, event.payment_ref, event.amount_minor) == (None, None, None, None)

    def test_a_real_full_refund_reverses_the_very_order_that_was_bought(self):
        (bought,) = deliver(fixture("order_paid_purchase"))
        (refunded,) = deliver(fixture("order_refunded_full"), event_id="msg_real_2")

        assert refunded.kind is EventKind.PAYMENT_REFUNDED
        assert refunded.payment_ref == bought.payment_ref, "the refund finds the grant it takes back"
        assert refunded.amount_minor == bought.amount_minor

    def test_a_real_partial_refund_is_never_reported_as_a_full_one(self):
        (event,) = deliver(fixture("order_refunded_partial"))

        assert event.kind is EventKind.PAYMENT_PARTIALLY_REFUNDED and event.amount_minor == 300

    def test_a_real_refund_object_is_ignored_because_the_order_event_already_carries_it(self):
        """`refund.created` and `order.refunded` both fire; acting on both would reverse a refund twice."""
        (event,) = deliver(fixture("refund_created"))

        assert event.kind is EventKind.IGNORED

    @pytest.mark.parametrize("name", ["order_paid_purchase", "order_refunded_full"])
    def test_the_buyers_name_address_and_email_never_reach_the_stored_form(self, name):
        (event,) = deliver(fixture(name))

        stored = json.dumps(event.stored()).lower()
        for detail in ("zetterlund", "monica", "@polar.sh", "billing_name", "billing_address"):
            assert detail not in stored, f"{detail!r} reached the stored payload"


class TestPurchases:
    def test_a_paid_one_time_order_is_a_purchase(self):
        (event,) = deliver(order())

        assert event.kind is EventKind.CREDITS_PURCHASED

    def test_the_amount_carried_is_what_the_buyer_paid_after_discounts_and_tax_not_the_net(self):
        """Informational only (the catalog decides the credits), but the figure on record should be the charge, not the pre-tax net."""
        (event,) = deliver(order(total_amount=1000, net_amount=900))

        assert event.amount_minor == 1000

    @pytest.mark.parametrize("status", ["pending", "draft", "void", "refunded", "partially_refunded", None, "PAID", True, 1])
    def test_only_a_paid_order_grants(self, status):
        """`order.created` can be pending and a paid event must be positively paid: anything else grants nothing."""
        (event,) = deliver(order(status=status))

        assert event.kind is EventKind.IGNORED

    @pytest.mark.parametrize("reason", ["subscription_create", "subscription_cycle", "subscription_update", "subscription_meter_cycle", None, "Purchase", "", 5])
    def test_only_a_one_time_purchase_grants(self, reason):
        (event,) = deliver(order(billing_reason=reason))

        assert event.kind is EventKind.IGNORED

    def test_an_order_with_no_single_product_has_no_catalog_entry_so_the_app_can_quarantine_it(self):
        (event,) = deliver(order(product_id=None))

        assert event.kind is EventKind.CREDITS_PURCHASED and event.product_ref is None

    def test_a_customer_is_read_from_the_nested_object_when_the_flat_id_is_absent(self):
        payload = order(customer_id=None, customer={"id": "cus_nested", "email": "x@example.com"})

        (event,) = deliver(payload)

        assert event.customer_ref == "cus_nested"

    @pytest.mark.parametrize("junk", [5, "", None, ["a"], {"id": "x"}])
    def test_an_odd_reference_is_no_reference_not_a_crash(self, junk):
        (event,) = deliver(order(customer_id=junk, product_id=junk, id=junk, customer=None))

        assert (event.customer_ref, event.product_ref, event.payment_ref) == (None, None, None)

    @pytest.mark.parametrize("amount", ["10.00", 10.5, True, None, [10]], ids=["string", "float", "boolean", "null", "list"])
    def test_an_amount_that_is_not_an_integer_is_not_carried(self, amount):
        """A JSON `true` is a Python int 1; carried as an amount it would read as one cent."""
        (event,) = deliver(order(total_amount=amount))

        assert event.amount_minor is None


class TestRefunds:
    @staticmethod
    def refunded(**overrides) -> dict:
        payload = order(**{"status": "refunded", "refunded_amount": 1000, **overrides})
        payload["type"] = "order.refunded"
        return payload

    def test_a_fully_refunded_order_is_a_full_refund_naming_the_payment_it_reverses(self):
        (event,) = deliver(self.refunded())

        assert event.kind is EventKind.PAYMENT_REFUNDED
        assert (event.customer_ref, event.payment_ref, event.amount_minor, event.product_ref) == ("cus_1", "ord_1", 1000, None)

    @pytest.mark.parametrize("status", ["partially_refunded", "paid", "pending", None, "REFUNDED", "Refunded", True, 1, ["refunded"]])
    def test_only_the_exact_status_refunded_means_fully_refunded(self, status):
        """When in doubt the safe reading is the one that quarantines for a person, not the one that claws everything back (D12)."""
        (event,) = deliver(self.refunded(status=status))

        assert event.kind is EventKind.PAYMENT_PARTIALLY_REFUNDED

    def test_the_amount_carried_is_the_running_refunded_total(self):
        (event,) = deliver(self.refunded(status="partially_refunded", refunded_amount=300))

        assert event.amount_minor == 300

    @pytest.mark.parametrize("reason", ["subscription_create", "subscription_cycle", "subscription_update"])
    def test_the_refund_of_a_renewal_reverses_no_pack_so_it_is_ignored(self, reason):
        (event,) = deliver(self.refunded(billing_reason=reason))

        assert event.kind is EventKind.IGNORED

    @pytest.mark.parametrize("reason", [None, "purchase", "something_new", 5])
    def test_a_refund_of_anything_not_known_to_be_a_renewal_is_not_dropped(self, reason):
        """Dropping a refund silently leaves credits that were paid back; a quarantine for a person is the cheaper mistake."""
        (event,) = deliver(self.refunded(billing_reason=reason))

        assert event.kind is EventKind.PAYMENT_REFUNDED


class TestWhatItDoesNotUnderstand:
    @pytest.mark.parametrize(
        "event_type",
        ["order.created", "order.updated", "refund.created", "refund.updated", "checkout.created", "checkout.updated", "checkout.expired",
         "subscription.created", "subscription.cycled", "subscription.revoked", "customer.created", "benefit_grant.created", "product.updated"],
    )
    def test_every_other_event_is_ignored_and_keeps_no_references(self, event_type):
        payload = order()
        payload["type"] = event_type

        (event,) = deliver(payload)

        assert event.kind is EventKind.IGNORED
        assert (event.customer_ref, event.product_ref, event.payment_ref, event.amount_minor) == (None, None, None, None)
        assert event.raw_type == event_type

    def test_a_very_long_event_type_is_cut_for_the_inbox(self):
        payload = order()
        payload["type"] = "x" * 500

        (event,) = deliver(payload)

        assert len(event.raw_type) == 100

    @pytest.mark.parametrize("stamp", [None, "soon", 123, "", "2026-13-45T00:00:00Z"])
    def test_an_unreadable_timestamp_is_no_time_not_a_crash(self, stamp):
        payload = order()
        payload["timestamp"] = stamp

        (event,) = deliver(payload)

        assert event.occurred_at is None

    def test_a_timestamp_with_no_zone_is_read_as_utc(self):
        payload = order()
        payload["timestamp"] = "2026-10-08T14:10:11"

        (event,) = deliver(payload)

        assert event.occurred_at.isoformat() == "2026-10-08T14:10:11+00:00"


class TestAnAuthenticBodyInTheWrongShape:
    @pytest.mark.parametrize(
        "payload",
        [[], "a string", 5, {}, {"type": "order.paid"}, {"type": "order.paid", "data": "no"}, {"type": "order.paid", "data": []},
         {"type": "", "data": {}}, {"type": 5, "data": {}}, {"data": {}}],
    )
    def test_it_is_an_invalid_payload_never_a_forgery_and_never_a_crash(self, payload):
        with pytest.raises(InvalidPayload):
            deliver(payload)

    def test_a_body_that_is_not_json_is_an_invalid_payload(self):
        with pytest.raises(InvalidPayload):
            deliver(b"<html>not json</html>")

    def test_an_event_id_too_long_for_the_inbox_is_an_invalid_payload(self):
        with pytest.raises(InvalidPayload):
            deliver(order(), event_id="m" * 256)

    def test_the_longest_event_id_the_inbox_takes_is_accepted(self):
        (event,) = deliver(order(), event_id="m" * 255)

        assert len(event.event_id) == 255


CUSTOMER = BillingCustomer("acme-tenant", "polar", "cus_9")
PRODUCT = CreditProduct("polar", "prod_pack_100", __import__("decimal").Decimal("100"))


def with_api(api: FakePolarApi | None = None, **kwargs) -> tuple[PolarProvider, FakePolarApi]:
    api = api or FakePolarApi()
    kwargs.setdefault("access_token", api.token)
    kwargs.setdefault("environment", "sandbox")
    return PolarProvider(NEW_SECRET, transport=api.transport, **kwargs), api


async def checkout(p: PolarProvider, key: str = "k1", *, customer: BillingCustomer = CUSTOMER, product: CreditProduct = PRODUCT):
    return await p.create_checkout(customer, product, idempotency_key=key, success_url="https://app/ok", cancel_url="https://app/no")


def methods(api: FakePolarApi) -> list[str]:
    return [r.method for r in api.requests]


class TestTheCheckoutRequest:
    async def test_it_asks_for_the_packs_product_for_the_polar_customer_and_remembers_the_attempt(self):
        p, api = with_api()

        await checkout(p, "attempt-7")

        (body,) = api.bodies
        assert body == {
            "products": ["prod_pack_100"], "customer_id": "cus_9", "success_url": "https://app/ok", "return_url": "https://app/no",
            "metadata": {ATTEMPT_KEY: "attempt-7"},
        }

    async def test_it_authenticates_with_the_access_token_at_the_documented_endpoint(self):
        p, api = with_api()

        await checkout(p)

        create = api.requests[-1]
        assert (create.method, create.url.host, create.url.path) == ("POST", "sandbox-api.polar.sh", "/v1/checkouts/")
        assert create.headers["authorization"] == f"Bearer {api.token}"

    async def test_it_does_not_pretend_polar_has_idempotency_by_sending_a_header_polar_ignores(self):
        p, api = with_api()

        await checkout(p)

        assert all("idempotency-key" not in r.headers for r in api.requests)

    async def test_neither_an_amount_nor_a_credit_count_nor_a_tenant_is_sent(self):
        """What a pack is WORTH is the catalog's decision and what it COSTS is the product's price: the request names the product and nothing else."""
        p, api = with_api()

        await checkout(p)

        wire = json.dumps([api.bodies, [str(r.url) for r in api.requests]])
        assert "acme-tenant" not in wire and "credits" not in wire and "amount" not in wire

    async def test_it_returns_the_sessions_id_and_hosted_url(self):
        p, api = with_api()

        session = await checkout(p)

        assert session.session_ref in api.sessions and session.url.startswith("https://sandbox.polar.sh/checkout/")

    @pytest.mark.parametrize(("environment", "host"), [("sandbox", "sandbox-api.polar.sh"), ("production", "api.polar.sh")])
    async def test_the_environment_picks_the_api(self, environment, host):
        p, api = with_api(environment=environment)

        await checkout(p)

        assert {r.url.host for r in api.requests} == {host}

    def test_an_unknown_environment_is_refused_not_defaulted_to_production(self):
        with pytest.raises(ValueError, match="environment"):
            PolarProvider(NEW_SECRET, environment="staging")


class TestARetryOfOneAttemptIsOnePurchase:
    """Polar has no idempotency for this call, so the adapter looks before it creates."""

    async def test_the_same_key_twice_is_the_same_session_and_one_creation(self):
        p, api = with_api()

        first = await checkout(p, "attempt-1")
        again = await checkout(p, "attempt-1")

        assert again == first and len(api.sessions) == 1 and methods(api) == ["GET", "POST", "GET"]

    async def test_a_different_key_is_a_different_purchase_attempt(self):
        p, api = with_api()

        first = await checkout(p, "attempt-1")
        second = await checkout(p, "attempt-2")

        assert second.session_ref != first.session_ref and len(api.sessions) == 2

    async def test_the_search_is_for_this_customer_and_this_product_and_never_returns_anyone_elses_session(self):
        p, api = with_api()
        mine = await checkout(p, "attempt-1")

        theirs = await checkout(p, "attempt-1", customer=BillingCustomer("other", "polar", "cus_other"))
        other_product = await checkout(p, "attempt-1", product=CreditProduct("polar", "prod_other", __import__("decimal").Decimal("5")))

        assert len({mine.session_ref, theirs.session_ref, other_product.session_ref}) == 3
        searches = [r.url.params for r in api.requests if r.method == "GET"]
        assert all(s["customer_id"] and s["product_id"] for s in searches), "an unscoped search could hand one buyer another's session"

    async def test_the_search_asks_for_the_newest_hundred(self):
        p, api = with_api()

        await checkout(p)

        search = next(r for r in api.requests if r.method == "GET").url.params
        assert (search["limit"], search["sorting"]) == ("100", "-created_at")

    async def test_an_attempt_that_is_already_paid_is_returned_not_offered_again(self):
        p, api = with_api()
        first = await checkout(p, "attempt-1")
        api.set_status(first.session_ref, "succeeded")

        again = await checkout(p, "attempt-1")

        assert again == first and len(api.sessions) == 1

    @pytest.mark.parametrize("dead", ["expired", "failed"])
    async def test_an_attempt_that_can_no_longer_be_paid_gets_a_fresh_session_under_the_same_key(self, dead):
        p, api = with_api()
        first = await checkout(p, "attempt-1")
        api.set_status(first.session_ref, dead)

        fresh = await checkout(p, "attempt-1")
        again = await checkout(p, "attempt-1")

        assert fresh.session_ref != first.session_ref and len(api.sessions) == 2
        assert again == fresh, "the newest match wins, so a third try does not create a third"

    async def test_an_older_open_session_of_the_attempt_beyond_the_search_is_not_found(self):
        """The search is bounded (the newest 100). This pins the bound as a bound, so changing it is a decision and not an accident."""
        p, api = with_api()
        first = await checkout(p, "attempt-1")
        for n in range(100):
            await checkout(p, f"filler-{n}")

        again = await checkout(p, "attempt-1")

        assert again.session_ref != first.session_ref

    async def test_a_failed_search_creates_nothing_because_creating_blind_is_how_a_retry_buys_twice(self):
        api = FakePolarApi()
        api.script(httpx.Response(500, json={"error": "InternalServerError"}))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.retryable is True and methods(api) == ["GET"] and not api.sessions

    @pytest.mark.parametrize("body", [{}, {"items": None}, {"items": "x"}, {"items": {"a": 1}}, [], "text"])
    async def test_a_search_answer_that_is_not_a_list_creates_nothing(self, body):
        api = FakePolarApi()
        api.script(httpx.Response(200, json=body))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.code == "bad_response" and methods(api) == ["GET"] and not api.sessions

    async def test_a_search_answer_that_is_not_json_creates_nothing(self):
        api = FakePolarApi()
        api.script(httpx.Response(200, content=b"<html>"))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.code == "bad_response" and not api.sessions

    @pytest.mark.parametrize("url", [None, "", 5])
    async def test_a_listed_attempt_with_no_usable_url_is_an_error_not_a_second_creation(self, url):
        api = FakePolarApi()
        api.script(httpx.Response(200, json={"items": [{"id": "chk_1", "status": "open", "url": url, "metadata": {ATTEMPT_KEY: "k1"}}]}))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p, "k1")

        assert caught.value.code == "bad_response" and methods(api) == ["GET"]

    async def test_listed_items_that_are_not_objects_are_skipped_not_a_crash(self):
        api = FakePolarApi()
        api.script(httpx.Response(200, json={"items": [None, 5, "x", {"metadata": None}, {"metadata": "no"}, {"metadata": {ATTEMPT_KEY: "other"}}]}))
        p, _ = with_api(api)

        session = await checkout(p, "k1")

        assert session.session_ref in api.sessions, "nothing matched, so one was created"


class TestARefusedCheckoutSaysWhetherToTryAgain:
    @pytest.mark.parametrize(
        ("status", "retryable"),
        [(400, False), (401, False), (403, False), (404, False), (422, False), (408, True), (409, True), (429, True), (500, True), (502, True), (503, True)],
    )
    async def test_the_status_decides_for_the_creation(self, status, retryable):
        api = FakePolarApi()
        api.script(httpx.Response(200, json={"items": []}), httpx.Response(status, json={"error": "SomeError", "detail": "words that must not be repeated"}))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.retryable is retryable and caught.value.status == status and caught.value.code == "SomeError"

    async def test_polars_own_words_and_the_token_never_reach_the_message(self):
        """A client error can quote what was sent, and the message ends up in logs."""
        api = FakePolarApi()
        p = PolarProvider(NEW_SECRET, access_token="polar_oat_wrong_token", environment="sandbox", transport=api.transport)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        message = str(caught.value)
        assert caught.value.status == 401 and caught.value.retryable is False
        assert "polar_oat" not in message and "human message" not in message and "invalid_token" in message

    async def test_a_422_names_the_field_and_not_polars_words(self):
        api = FakePolarApi()
        api.script(
            httpx.Response(200, json={"items": []}),
            httpx.Response(422, json={"detail": [{"loc": ["body", "products", 0], "msg": "Input should be a valid UUID, got 'prod_x'", "type": "uuid_parsing"}]}),
        )
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert "field products.0" in str(caught.value) and "valid UUID" not in str(caught.value) and caught.value.retryable is False

    @pytest.mark.parametrize("loc", [["body", "sk test abc"], ["body", "<script>"], ["body", "x" * 101], ["body"], [], "notalist", None])
    async def test_a_location_that_is_not_a_field_name_is_dropped_not_repeated(self, loc):
        api = FakePolarApi()
        api.script(httpx.Response(200, json={"items": []}), httpx.Response(422, json={"detail": [{"loc": loc, "msg": "m", "type": "t"}]}))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert "field" not in str(caught.value)
        if isinstance(loc, list) and len(loc) > 1:
            assert loc[1] not in str(caught.value)

    @pytest.mark.parametrize("error", ["has space", "x" * 65, "a;b", 5, ""])
    async def test_an_error_type_that_is_not_an_identifier_is_dropped(self, error):
        api = FakePolarApi()
        api.script(httpx.Response(200, json={"items": []}), httpx.Response(400, json={"error": error}))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.code is None and "HTTP 400)" in str(caught.value)

    @pytest.mark.parametrize("phase", ["search", "create"])
    async def test_a_network_failure_is_retryable_and_names_only_the_exception_class(self, phase):
        calls = []

        def unreachable(request):
            calls.append(request.method)
            if phase == "search" or len(calls) > 1:
                raise httpx.ConnectError("no route to host with token polar_oat_secret")
            return httpx.Response(200, json={"items": []})

        p = PolarProvider(NEW_SECRET, access_token="polar_oat_x", environment="sandbox", transport=httpx.MockTransport(unreachable))

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.retryable is True and caught.value.code == "network"
        assert "polar_oat_secret" not in str(caught.value) and "ConnectError" in str(caught.value)

    @pytest.mark.parametrize("body", [{}, {"id": "chk_1"}, {"url": "https://x"}, {"id": "", "url": ""}, {"id": 1, "url": 2}, [], "text"])
    async def test_a_creation_that_answers_with_no_usable_session_is_an_error_never_an_empty_session(self, body):
        api = FakePolarApi()
        api.script(httpx.Response(200, json={"items": []}), httpx.Response(201, json=body))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.code == "bad_response" and caught.value.retryable is False

    async def test_a_creation_answered_with_200_instead_of_201_is_still_a_session(self):
        api = FakePolarApi()
        api.script(httpx.Response(200, json={"items": []}), httpx.Response(200, json={"id": "chk_1", "url": "https://sandbox.polar.sh/checkout/x"}))
        p, _ = with_api(api)

        assert (await checkout(p)).session_ref == "chk_1"

    async def test_without_an_access_token_nothing_is_attempted(self):
        api = FakePolarApi()
        p, _ = with_api(api, access_token="")

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.code == "no_access_token" and caught.value.retryable is False
        assert api.requests == [], "a webhook-only deployment must not make a request it cannot authenticate"

    @pytest.mark.parametrize("key", ["", "k" * 256])
    async def test_an_idempotency_key_outside_the_bound_is_refused_before_any_request(self, key):
        p, api = with_api()

        with pytest.raises(CheckoutError) as caught:
            await checkout(p, key)

        assert caught.value.code == "bad_idempotency_key" and api.requests == []

    async def test_the_longest_key_is_accepted(self):
        p, api = with_api()

        await checkout(p, "k" * 255)

        assert api.bodies[0]["metadata"][ATTEMPT_KEY] == "k" * 255


class TestWhatItDeclares:
    def test_it_sells_a_pack_and_nothing_else_because_the_provider_is_never_told_what_was_consumed(self):
        """Spec D16: prepaid packs. The export outbox and worker stay off for Polar."""
        assert PolarProvider.capabilities == frozenset({Capability.CHECKOUT})

    def test_so_no_usage_is_ever_queued_for_it(self):
        assert providers.usage_export_providers(("polar",)) == ()

    async def test_the_capabilities_it_does_not_declare_say_so_instead_of_pretending(self):
        p = provider()

        with pytest.raises(NotImplementedError, match="USAGE_EXPORT"):
            await p.export_usage(CUSTOMER, [])
        with pytest.raises(NotImplementedError, match="BALANCE_READ"):
            await p.read_balance(CUSTOMER)

    def test_it_is_registered_under_its_own_name_and_builds_from_a_secret_alone(self):
        assert providers.FACTORIES["polar"] is PolarProvider
        assert providers.build("polar", NEW_SECRET).name == "polar"

    def test_the_token_and_the_environment_come_from_the_settings_when_they_are_not_passed(self, monkeypatch):
        monkeypatch.setattr("app.core.config.POLAR_ACCESS_TOKEN", "polar_oat_from_settings")
        monkeypatch.setattr("app.core.config.POLAR_ENVIRONMENT", "production")

        from_settings = PolarProvider(NEW_SECRET)

        assert from_settings._token == "polar_oat_from_settings" and "://api.polar.sh/" in from_settings._api_base
        assert PolarProvider(NEW_SECRET, access_token="explicit", environment="sandbox")._token == "explicit"
        assert PolarProvider(NEW_SECRET, access_token="", environment="sandbox")._token == "", "an explicit empty token is honoured, not replaced"
