"""The Stripe adapter (app/billing/providers/stripe.py, specs/010 T029a): what the shared contract suite cannot say about it.

tests/billing/test_provider_contract.py holds every adapter to the same promises (refuse a forgery, name no tenant, store no buyer
details, echo what checkout set). This file is what is particular to Stripe's wire formats: its signature header, its event and object
shapes, its checkout request and its error replies. Hermetic: the signing is computed in-process and the HTTP is `httpx.MockTransport`.

## Why the signature tests do not just agree with the code

The vectors below were generated by STRIPE'S OWN PYTHON LIBRARY (`stripe.WebhookSignature.generate_signature_header`, stripe 16.0.0), run in
a throwaway environment outside this repository's dependencies. If this adapter and a test harness both misread the documented scheme the
same way, only a header produced by someone else would show it. The official verifier also accepts the "rolled" header and refuses the stale
one at the same instants used here.
"""
import json

import httpx
import pytest

from app.billing import providers
from app.billing.providers.base import (
    BillingCustomer,
    Capability,
    CheckoutError,
    CreditProduct,
    EventKind,
    InvalidPayload,
    InvalidSignature,
)
from app.billing.providers.stripe import StripeProvider
from tests.billing.fake_stripe_api import FakeStripeApi

SECRET = "whsec_known_answer_not_a_real_secret"
T = 1_760_000_000
# --- generated by Stripe's own library ------------------------------------------------------------------------------------
KNOWN_BODY = b'{"created":1760000000,"data":{"object":{"id":"ch_1"}},"id":"evt_ka_1","object":"event","type":"charge.refunded"}'
KNOWN_HEADER = "t=1760000000,v1=6ca238bc00e761dbe7dc3adfae8622f3ccb46b9b369e7b38544e9c233fd1ef02"
# An OLD secret's signature first, then the right one, then Stripe's fake `v0` scheme: what a delivery looks like while a secret is rolled.
ROLLED_HEADER = (
    "t=1760000000,v1=603928041c2df8f5276d9543c8842171505b5914f092542c1b144926c08cc8e2,"
    "v1=6ca238bc00e761dbe7dc3adfae8622f3ccb46b9b369e7b38544e9c233fd1ef02,"
    "v0=6ffbb59b2300aae63f272406069a9788598b792a944a07aba816edb039989a39"
)
V0_ONLY_HEADER = "t=1760000000,v0=6ffbb59b2300aae63f272406069a9788598b792a944a07aba816edb039989a39"


def provider(now: float = T + 10, **kwargs) -> StripeProvider:
    return StripeProvider(SECRET, api_key=kwargs.pop("api_key", "sk_test_x"), clock=lambda: now, **kwargs)


def parse(p: StripeProvider, header: str | None, body: bytes = KNOWN_BODY):
    return p.parse_webhook({"Stripe-Signature": header} if header else {}, body)


class TestTheSignatureHeader:
    def test_a_header_generated_by_stripes_own_library_is_accepted(self):
        (event,) = parse(provider(), KNOWN_HEADER)

        assert event.event_id == "evt_ka_1" and event.raw_type == "charge.refunded"

    def test_a_rolled_secrets_header_with_an_old_signature_first_is_accepted_because_any_v1_may_match(self):
        assert parse(provider(), ROLLED_HEADER)

    def test_the_fake_v0_scheme_alone_is_never_enough(self):
        """Stripe adds a `v0` signature to TEST events; accepting it would let anyone who knows the (public) fake scheme in."""
        with pytest.raises(InvalidSignature):
            parse(provider(), V0_ONLY_HEADER)

    def test_only_the_v1_label_counts_even_for_a_signature_that_is_arithmetically_right(self):
        """The known-answer v0 above fails on its VALUE, which would also stop an adapter that wrongly accepted the label. This
        one carries the CORRECT v1 MAC under the `v0` label, so only the scheme label can be what refuses it."""
        right_mac = KNOWN_HEADER.split("v1=")[1]

        with pytest.raises(InvalidSignature):
            parse(provider(), f"t={T},v0={right_mac}")

    def test_a_header_signed_with_another_secret_is_refused(self):
        with pytest.raises(InvalidSignature):
            parse(StripeProvider("whsec_someone_else", api_key="x", clock=lambda: T + 10), KNOWN_HEADER)

    @pytest.mark.parametrize(
        "header",
        ["", "garbage", "t=,v1=", f"v1={KNOWN_HEADER.split('v1=')[1]}", "t=1760000000", "t=notanumber,v1=abc", ",,,", "t=1760000000,v1="],
        ids=["empty", "garbage", "blank-values", "no-timestamp", "no-signature", "bad-timestamp", "commas", "empty-signature"],
    )
    def test_a_malformed_header_is_refused_not_a_crash(self, header):
        with pytest.raises(InvalidSignature):
            parse(provider(), header)

    def test_the_timestamp_is_bound_into_the_mac_so_it_cannot_be_moved_to_make_an_old_delivery_look_fresh(self):
        moved = KNOWN_HEADER.replace("t=1760000000", "t=1760000300")

        with pytest.raises(InvalidSignature):
            parse(provider(now=T + 310), moved)

    def test_the_window_refuses_a_stale_delivery_and_accepts_one_at_the_edge(self):
        assert parse(provider(now=T + 300), KNOWN_HEADER)
        with pytest.raises(InvalidSignature):
            parse(provider(now=T + 301), KNOWN_HEADER)

    def test_a_future_dated_delivery_is_not_refused_exactly_as_stripes_own_verifier_does_not(self):
        """A captured delivery can only be in the PAST, so a symmetric check adds nothing against replay and would reject Stripe's real
        deliveries whenever this machine's clock runs behind. The MAC still has to be right."""
        assert parse(provider(now=T - 3600), KNOWN_HEADER)

    def test_header_names_are_case_insensitive(self):
        assert provider().parse_webhook({"STRIPE-SIGNATURE": KNOWN_HEADER}, KNOWN_BODY)

    def test_a_body_altered_after_signing_is_refused(self):
        with pytest.raises(InvalidSignature):
            parse(provider(), KNOWN_HEADER, KNOWN_BODY.replace(b"ch_1", b"ch_2"))

    def test_a_tolerance_of_zero_is_refused_because_it_disables_the_check(self):
        with pytest.raises(ValueError, match="tolerance"):
            StripeProvider(SECRET, tolerance_seconds=0)

    def test_a_provider_with_no_secret_cannot_exist(self):
        with pytest.raises(ValueError, match="secret"):
            StripeProvider("")


def _event(event_type: str, obj: dict, event_id: str = "evt_1", created: int | None = T) -> dict:
    body = {"id": event_id, "object": "event", "type": event_type, "data": {"object": obj}}
    if created is not None:
        body["created"] = created
    return body


def normalize(payload: dict | list | str, p: StripeProvider | None = None):
    """Sign `payload` the documented way and parse it, so only the mapping is under test."""
    import hashlib
    import hmac

    p = p or provider(now=T)
    body = json.dumps(payload).encode()
    mac = hmac.new(SECRET.encode(), f"{T}.".encode() + body, hashlib.sha256).hexdigest()
    return p.parse_webhook({"stripe-signature": f"t={T},v1={mac}"}, body)


PAID = {
    "id": "cs_test_1", "object": "checkout.session", "mode": "payment", "status": "complete", "payment_status": "paid",
    "customer": "cus_1", "payment_intent": "pi_1", "amount_total": 500, "currency": "usd", "metadata": {"product_ref": "price_pack_100"},
}


class TestPurchases:
    def test_a_paid_one_time_session_is_a_purchase_with_every_reference_the_app_needs(self):
        (event,) = normalize(_event("checkout.session.completed", PAID))

        assert event.kind is EventKind.CREDITS_PURCHASED
        assert (event.customer_ref, event.product_ref, event.payment_ref) == ("cus_1", "price_pack_100", "pi_1")
        assert (event.amount_minor, event.currency, event.raw_type) == (500, "usd", "checkout.session.completed")
        assert event.occurred_at.isoformat() == "2025-10-09T08:53:20+00:00"

    def test_a_session_whose_payment_has_not_cleared_grants_nothing_yet(self):
        """A delayed payment method completes the session UNPAID; granting now would give credits for money that may never arrive."""
        (event,) = normalize(_event("checkout.session.completed", {**PAID, "payment_status": "unpaid"}))

        assert event.kind is EventKind.IGNORED

    def test_the_delayed_payment_that_finally_clears_is_the_event_that_grants(self):
        (event,) = normalize(_event("checkout.session.async_payment_succeeded", PAID))

        assert event.kind is EventKind.CREDITS_PURCHASED and event.payment_ref == "pi_1"

    @pytest.mark.parametrize("mode", ["subscription", "setup"])
    def test_only_one_time_payments_are_sold(self, mode):
        (event,) = normalize(_event("checkout.session.completed", {**PAID, "mode": mode}))

        assert event.kind is EventKind.IGNORED

    def test_a_session_this_app_did_not_create_has_no_product_so_the_app_can_quarantine_it_rather_than_guess(self):
        (event,) = normalize(_event("checkout.session.completed", {**PAID, "metadata": {}}))

        assert event.kind is EventKind.CREDITS_PURCHASED and event.product_ref is None

    def test_a_guest_checkout_has_no_customer_for_the_app_to_link(self):
        (event,) = normalize(_event("checkout.session.completed", {**PAID, "customer": None}))

        assert event.customer_ref is None

    def test_an_expanded_reference_is_read_as_its_id(self):
        (event,) = normalize(_event("checkout.session.completed", {**PAID, "customer": {"id": "cus_exp", "email": "x@example.com"}}))

        assert event.customer_ref == "cus_exp"

    @pytest.mark.parametrize("junk", [{"product_ref": 5}, {"product_ref": ""}, "not-a-dict", None, ["a"]])
    def test_odd_metadata_is_no_product_not_a_crash(self, junk):
        (event,) = normalize(_event("checkout.session.completed", {**PAID, "metadata": junk}))

        assert event.product_ref is None

    @pytest.mark.parametrize("amount", ["5.00", 5.5, True, None, [5]], ids=["string", "float", "boolean", "null", "list"])
    def test_an_amount_that_is_not_an_integer_is_not_carried(self, amount):
        """A JSON `true` is a Python int 1; carried as an amount it would read as one cent."""
        (event,) = normalize(_event("checkout.session.completed", {**PAID, "amount_total": amount}))

        assert event.amount_minor is None


CHARGE = {"id": "ch_1", "object": "charge", "amount": 1000, "amount_refunded": 1000, "refunded": True, "customer": "cus_1", "payment_intent": "pi_1", "currency": "usd"}


class TestRefundsAndDisputes:
    def test_a_fully_refunded_charge_is_a_full_refund_that_names_the_payment_it_reverses(self):
        (event,) = normalize(_event("charge.refunded", CHARGE))

        assert event.kind is EventKind.PAYMENT_REFUNDED
        assert (event.customer_ref, event.payment_ref, event.amount_minor) == ("cus_1", "pi_1", 1000)

    def test_a_partial_refund_is_never_reported_as_a_full_one(self):
        """`charge.refunded` fires for both; reporting a partial refund as full would take back every credit (D12)."""
        (event,) = normalize(_event("charge.refunded", {**CHARGE, "amount_refunded": 300, "refunded": False}))

        assert event.kind is EventKind.PAYMENT_PARTIALLY_REFUNDED and event.amount_minor == 300

    @pytest.mark.parametrize("refunded", [None, "true", 1, "yes"])
    def test_only_a_literal_true_means_fully_refunded(self, refunded):
        """When in doubt the safe reading is the one that quarantines for a person, not the one that claws everything back."""
        (event,) = normalize(_event("charge.refunded", {**CHARGE, "refunded": refunded}))

        assert event.kind is EventKind.PAYMENT_PARTIALLY_REFUNDED

    def test_a_dispute_is_opened_and_closed_by_the_payment_it_concerns(self):
        # Stripe's Dispute object has no `customer`; one is planted here to show the adapter reads only the fields it is documented to.
        dispute = {"id": "du_1", "object": "dispute", "charge": "ch_1", "payment_intent": "pi_1", "amount": 1000, "currency": "usd", "customer": "cus_planted"}

        (opened,) = normalize(_event("charge.dispute.created", dispute))
        (closed,) = normalize(_event("charge.dispute.closed", dispute, event_id="evt_2"))

        assert (opened.kind, closed.kind) == (EventKind.DISPUTE_OPENED, EventKind.DISPUTE_CLOSED)
        assert opened.payment_ref == "pi_1" and opened.customer_ref is None, "a Dispute has no customer field"

    def test_a_dispute_on_a_charge_with_no_payment_intent_has_no_payment_ref(self):
        (event,) = normalize(_event("charge.dispute.created", {"id": "du_1", "charge": "ch_1", "payment_intent": None, "amount": 5}))

        assert event.kind is EventKind.DISPUTE_OPENED and event.payment_ref is None


class TestWhatItDoesNotUnderstand:
    @pytest.mark.parametrize(
        "event_type",
        ["customer.created", "invoice.paid", "payment_intent.succeeded", "checkout.session.expired", "checkout.session.async_payment_failed", "charge.succeeded", "refund.created"],
    )
    def test_every_other_event_is_ignored_and_keeps_no_references(self, event_type):
        (event,) = normalize(_event(event_type, {"id": "x", "customer": "cus_1", "payment_intent": "pi_1", "metadata": {"product_ref": "p"}}))

        assert event.kind is EventKind.IGNORED
        assert (event.customer_ref, event.product_ref, event.payment_ref, event.amount_minor) == (None, None, None, None)
        assert event.raw_type == event_type

    def test_a_very_long_event_type_is_cut_for_the_inbox(self):
        (event,) = normalize(_event("x" * 500, {}))

        assert len(event.raw_type) == 100

    @pytest.mark.parametrize("created", [None, "soon", 10**30])
    def test_an_unreadable_created_time_is_no_time_not_a_crash(self, created):
        (event,) = normalize(_event("customer.created", {}, created=created))

        assert event.occurred_at is None


class TestAnAuthenticBodyInTheWrongShape:
    @pytest.mark.parametrize(
        "payload",
        [[], "a string", 5, {}, {"id": "e", "type": "x"}, {"id": "e", "type": "x", "data": {}}, {"id": "e", "type": "x", "data": {"object": "no"}},
         {"id": "", "type": "x", "data": {"object": {}}}, {"id": "e", "type": "", "data": {"object": {}}}, {"id": 1, "type": "x", "data": {"object": {}}}],
    )
    def test_it_is_an_invalid_payload_never_a_forgery_and_never_a_crash(self, payload):
        with pytest.raises(InvalidPayload):
            normalize(payload)

    def test_a_body_that_is_not_json_is_an_invalid_payload(self):
        import hashlib
        import hmac

        body = b"<html>not json</html>"
        mac = hmac.new(SECRET.encode(), f"{T}.".encode() + body, hashlib.sha256).hexdigest()

        with pytest.raises(InvalidPayload):
            provider(now=T).parse_webhook({"stripe-signature": f"t={T},v1={mac}"}, body)


CUSTOMER = BillingCustomer("acme-tenant", "stripe", "cus_9")
PRODUCT = CreditProduct("stripe", "price_pack_100", __import__("decimal").Decimal("100"))


def with_api(api: FakeStripeApi | None = None, **kwargs) -> tuple[StripeProvider, FakeStripeApi]:
    api = api or FakeStripeApi()
    return StripeProvider(SECRET, api_key=kwargs.pop("api_key", api.api_key), transport=api.transport, **kwargs), api


async def checkout(p: StripeProvider, key: str = "k1"):
    return await p.create_checkout(CUSTOMER, PRODUCT, idempotency_key=key, success_url="https://app/ok", cancel_url="https://app/no")


class TestTheCheckoutRequest:
    async def test_it_asks_for_one_unit_of_the_packs_price_for_the_stripe_customer(self):
        p, api = with_api()

        await checkout(p)

        (form,) = api.forms
        assert form == {
            "mode": "payment", "line_items[0][price]": "price_pack_100", "line_items[0][quantity]": "1", "customer": "cus_9",
            "success_url": "https://app/ok", "cancel_url": "https://app/no", "metadata[product_ref]": "price_pack_100",
        }

    async def test_it_authenticates_with_the_secret_key_and_sends_the_idempotency_key_to_the_documented_endpoint(self):
        p, api = with_api()

        await checkout(p, "attempt-77")

        (request,) = api.requests
        assert (request.method, request.url.host, request.url.path) == ("POST", "api.stripe.com", "/v1/checkout/sessions")
        assert request.headers["authorization"] == f"Bearer {api.api_key}"
        assert request.headers["idempotency-key"] == "attempt-77"

    async def test_neither_an_amount_nor_a_credit_count_nor_a_tenant_is_sent(self):
        """What a pack is WORTH is the catalog's decision and what it COSTS is the price's: the request names the price and nothing else."""
        p, api = with_api()

        await checkout(p)

        wire = json.dumps(api.forms)
        assert "acme-tenant" not in wire and "credits" not in wire and "amount" not in wire and "unit_amount" not in wire

    async def test_it_returns_the_sessions_id_and_hosted_url(self):
        p, _ = with_api()

        session = await checkout(p)

        assert session.session_ref == "cs_test_0001" and session.url == "https://checkout.stripe.test/c/pay/cs_test_0001"

    async def test_the_same_key_with_different_parameters_is_refused_not_a_second_purchase(self):
        p, api = with_api()
        await checkout(p, "k1")

        with pytest.raises(CheckoutError) as caught:
            await p.create_checkout(CUSTOMER, PRODUCT, idempotency_key="k1", success_url="https://elsewhere/ok", cancel_url="https://app/no")

        assert caught.value.retryable is False and caught.value.code == "idempotency_error"
        assert len(api.sessions) == 1


class TestARefusedCheckoutSaysWhetherToTryAgain:
    @pytest.mark.parametrize(
        ("status", "retryable"),
        [(400, False), (401, False), (402, False), (403, False), (404, False), (409, True), (429, True), (500, True), (502, True), (503, True)],
    )
    async def test_the_status_decides(self, status, retryable):
        api = FakeStripeApi()
        api.script(httpx.Response(status, json={"error": {"type": "api_error", "code": "some_code", "message": "words that must not be repeated"}}))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.retryable is retryable and caught.value.status == status and caught.value.code == "some_code"

    async def test_stripes_own_words_and_the_key_never_reach_the_message(self):
        """A client error can quote a key fragment or a URL, and the message ends up in logs."""
        api = FakeStripeApi()
        api.script(httpx.Response(401, json={"error": {"type": "invalid_request_error", "message": "Invalid API Key provided: sk_test_****abcd"}}))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert "sk_test" not in str(caught.value) and "Invalid API Key" not in str(caught.value)
        assert "401" in str(caught.value) and "invalid_request_error" in str(caught.value)

    async def test_the_name_of_the_field_stripe_objected_to_is_reported_so_a_400_can_be_diagnosed(self):
        api = FakeStripeApi()
        api.script(httpx.Response(400, json={"error": {"type": "invalid_request_error", "code": "resource_missing", "param": "line_items[0][price]", "message": "No such price: 'price_x'"}}))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert "field line_items[0][price]" in str(caught.value) and "No such price" not in str(caught.value)

    @pytest.mark.parametrize("param", ["sk_test_abc def", "has a space", "x" * 101, "<script>", "a;b", "", 5])
    async def test_a_param_that_is_not_a_field_name_is_dropped_not_repeated(self, param):
        api = FakeStripeApi()
        api.script(httpx.Response(400, json={"error": {"type": "invalid_request_error", "param": param}}))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert "field" not in str(caught.value)
        if isinstance(param, str) and param:
            assert param not in str(caught.value)

    async def test_a_network_failure_is_retryable(self):
        def unreachable(request):
            raise httpx.ConnectError("no route to host api.stripe.com with key sk_test_secret")

        p = StripeProvider(SECRET, api_key="sk_test_x", transport=httpx.MockTransport(unreachable))

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.retryable is True and caught.value.code == "network"
        assert "sk_test_secret" not in str(caught.value), "only the exception CLASS is reported"

    @pytest.mark.parametrize("body", [{}, {"id": "cs_1"}, {"url": "https://x"}, {"id": "", "url": ""}, {"id": 1, "url": 2}, [], "text"])
    async def test_a_200_with_no_usable_session_is_an_error_never_an_empty_session(self, body):
        api = FakeStripeApi()
        api.script(httpx.Response(200, json=body))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.code == "bad_response" and caught.value.retryable is False

    async def test_a_200_that_is_not_json_is_the_same_error(self):
        api = FakeStripeApi()
        api.script(httpx.Response(200, content=b"<html>"))
        p, _ = with_api(api)

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.code == "bad_response"

    async def test_without_an_api_key_nothing_is_attempted(self):
        api = FakeStripeApi()
        p, _ = with_api(api, api_key="")

        with pytest.raises(CheckoutError) as caught:
            await checkout(p)

        assert caught.value.code == "no_api_key" and caught.value.retryable is False
        assert api.requests == [], "a webhook-only deployment must not make a request it cannot authenticate"

    @pytest.mark.parametrize("key", ["", "k" * 256])
    async def test_an_idempotency_key_stripe_would_refuse_is_refused_here_first(self, key):
        p, api = with_api()

        with pytest.raises(CheckoutError) as caught:
            await checkout(p, key)

        assert caught.value.code == "bad_idempotency_key" and api.requests == []

    async def test_the_longest_key_stripe_allows_is_sent(self):
        p, api = with_api()

        await checkout(p, "k" * 255)

        assert len(api.requests[0].headers["idempotency-key"]) == 255


class TestWhatItDeclares:
    def test_it_sells_a_pack_and_nothing_else_because_the_provider_is_never_told_what_was_consumed(self):
        """Spec D16: prepaid packs. The export outbox and worker stay off for Stripe."""
        assert StripeProvider.capabilities == frozenset({Capability.CHECKOUT})

    def test_so_no_usage_is_ever_queued_for_it(self):
        assert providers.usage_export_providers(("stripe",)) == ()

    async def test_the_capabilities_it_does_not_declare_say_so_instead_of_pretending(self):
        p = provider()

        with pytest.raises(NotImplementedError, match="USAGE_EXPORT"):
            await p.export_usage(CUSTOMER, [])
        with pytest.raises(NotImplementedError, match="BALANCE_READ"):
            await p.read_balance(CUSTOMER)

    def test_it_is_registered_under_its_own_name_and_builds_from_a_secret_alone(self):
        assert providers.FACTORIES["stripe"] is StripeProvider
        assert providers.build("stripe", "whsec_x").name == "stripe"

    def test_the_api_key_comes_from_the_settings_when_it_is_not_passed(self, monkeypatch):
        monkeypatch.setattr("app.core.config.STRIPE_API_KEY", "sk_test_from_settings")

        assert StripeProvider(SECRET)._api_key == "sk_test_from_settings"
        assert StripeProvider(SECRET, api_key="explicit")._api_key == "explicit"
        assert StripeProvider(SECRET, api_key="")._api_key == "", "an explicit empty key is honoured, not replaced"
