"""The Stripe adapter: sells a prepaid credit pack and tells the app it was paid (specs/010 T029a, D16).

Under the prepaid-packs model (D16) the provider takes the money and nothing more: it is never told what was consumed, so this
adapter declares `CHECKOUT` and nothing else (no `USAGE_EXPORT`, no `BALANCE_READ`). It translates two wire formats and holds no
business rule: a Checkout Session going out, and a signed webhook coming in.

## What was checked against Stripe, and how

Every claim below is from Stripe's own documentation (read 2026-10-08) or from a run against a Stripe SANDBOX, not from memory.

  * **The signature.** `Stripe-Signature: t=<unix>,v1=<hex>[,v1=<hex>][,v0=<hex>]`; the MAC is HMAC-SHA256, keyed with the endpoint's
    `whsec_...` secret, over `"<t>." + <raw body>`. Several `v1` appear while a secret is being rolled (one per active secret), and
    `v0` is a fake scheme Stripe adds to test events, which must be ignored. Stripe's official Python library is the ORACLE for the
    scheme: `tests/billing/test_stripe_adapter.py` holds known-answer headers generated by it, so this code and its test harness
    cannot merely agree with each other. The official verifier checks the MAC first and rejects only a STALE timestamp (default
    tolerance 300 s); a future-dated one is not rejected, because a captured delivery can only be in the past and a symmetric check
    would fail Stripe's real deliveries whenever this clock runs behind. That is mirrored here (the `fake` adapter is symmetric).
  * **The events**, by type (docs.stripe.com/api/events/types): `checkout.session.completed` ("a Checkout Session has been successfully
    completed"; its `payment_status` is `paid` or, for a delayed payment method, `unpaid`), `checkout.session.async_payment_succeeded`
    (the delayed method finally paid), `charge.refunded` ("whenever a charge is refunded, including partial refunds"), and
    `charge.dispute.created` / `charge.dispute.closed`. A Charge's `refunded` is true only when it is FULLY refunded
    (docs.stripe.com/api/charges/object), which is exactly the distinction the app needs between `PAYMENT_REFUNDED` and
    `PAYMENT_PARTIALLY_REFUNDED`; a Dispute has no `customer`, only a `charge` and a (nullable) `payment_intent`.
  * **Idempotency** (docs.stripe.com/api/idempotent_requests): the `Idempotency-Key` header on a POST, up to 255 characters, kept at
    least 24 hours; the first result (an error included) is replayed for the same key and the same parameters, and the same key with
    different parameters is an error.

  * **Against a real sandbox, by hand** while writing this (the repeatable test tier is the follow-up PR): a delivery signed by `stripe listen`
    carries `t`, `v1` AND `v0` and verifies here; the Checkout request below is accepted and returns the session shape the in-repo fake assumes.
    One finding that no document states plainly: with MANAGED PAYMENTS on (the default for a new account, and for the sandbox used here) Stripe
    refuses a Checkout line item whose Product has no `tax_code` ("the product tax code is missing", HTTP 400). That is catalog setup, not a
    request this adapter can fix; set an eligible code on the Product behind each pack's Price.

## How a purchase is tied to a refund and to a catalog entry

`BillingEvent.payment_ref` is the PaymentIntent id. A completed Checkout Session carries it as `payment_intent` (null until the session
completes), and a refunded Charge carries the same id, so a refund finds the grant it takes back. The catalog entry
(`credit_products.product_ref`) is the Stripe PRICE id, because that is what a Checkout line item needs; it travels to the webhook in
the session's `metadata.product_ref`, which `create_checkout` sets. A session this app did not create has no such metadata and so no
product: the app quarantines it as `unknown_product` rather than guessing.

## What this adapter must never do

Name a tenant, or let a payload decide an amount (`BillingEvent` has no field for either, on purpose), keep buyer details (the
inbox stores the normalized whitelist, never the body), or put a tenant on the wire to Stripe (the customer is identified by Stripe's
own id, and the link to a tenant is the app's table). An error from Stripe is reported by status, error type and code, never by its
message: a client error can carry a key fragment or a URL.

## Not done here, and said so

  * Subscriptions and invoices are ignored (the model is one-time packs). A `checkout.session.completed` in `subscription` mode is
    IGNORED, not granted.
  * Nothing calls `create_checkout` yet: there is no route that starts a purchase (no checkout UI is built, spec "not built"), so
    it is reachable from the sandbox test and from code only.
"""
import hashlib
import hmac
import json
import re
import time
from collections.abc import Callable, Mapping, Sequence
from datetime import UTC, datetime
from typing import Any

import httpx

from app.billing.providers.base import (
    BillingCustomer,
    BillingEvent,
    Capability,
    CheckoutError,
    CheckoutSession,
    CreditProduct,
    EventKind,
    ExportResult,
    InvalidPayload,
    InvalidSignature,
    UsageEvent,
)

SIGNATURE_HEADER = "stripe-signature"
TOLERANCE_SECONDS = 300  # Stripe's library default
API_BASE = "https://api.stripe.com"
REQUEST_TIMEOUT_SECONDS = 30.0

_PAID = frozenset({"checkout.session.completed", "checkout.session.async_payment_succeeded"})
# Stripe's `param` names the request field it objected to ("line_items[0][price]"). It is a field NAME, not free text, so it is safe to
# repeat; anything that does not look like one is dropped rather than trusted.
_PARAM = re.compile(r"[A-Za-z0-9_.\[\]]{1,100}")


class StripeProvider:
    name = "stripe"
    # On the CLASS, so the usage-event write can ask which providers bill on usage without a secret or an instance. Prepaid packs
    # (D16): the provider is never sent usage.
    capabilities: frozenset[Capability] = frozenset({Capability.CHECKOUT})

    def __init__(
        self,
        secret: str,
        *,
        api_key: str | None = None,
        clock: Callable[[], float] = time.time,
        tolerance_seconds: int = TOLERANCE_SECONDS,
        transport: httpx.AsyncBaseTransport | None = None,
        api_base: str = API_BASE,
    ):
        if not secret:
            raise ValueError("a provider needs a webhook secret")
        if tolerance_seconds <= 0:
            raise ValueError("a tolerance of 0 disables the replay check (Stripe's own docs warn against it)")
        self._secret = secret.encode()
        self._clock = clock
        self._tolerance = tolerance_seconds
        self._transport = transport
        self._api_base = api_base
        if api_key is None:
            from app.core.config import (
                STRIPE_API_KEY,  # read at construction, not import: tests re-point the settings
            )

            api_key = STRIPE_API_KEY
        self._api_key = api_key or ""

    # --- the webhook, inbound ---------------------------------------------------------------------------

    def parse_webhook(self, headers: Mapping[str, str], body: bytes) -> list[BillingEvent]:
        self._verify({k.lower(): v for k, v in headers.items()}, body)
        try:
            data = json.loads(body)
        except ValueError as exc:
            raise InvalidPayload("body is not JSON") from exc
        obj = (data.get("data") or {}).get("object") if isinstance(data, dict) else None
        if not isinstance(data, dict) or not _text(data.get("id")) or not _text(data.get("type")) or not isinstance(obj, dict):
            raise InvalidPayload("body is not a Stripe event")
        raw_type = data["type"]
        kind, customer, product, payment, amount, currency = _normalize(raw_type, obj)
        return [
            BillingEvent(
                provider=self.name,
                event_id=data["id"],
                kind=kind,
                customer_ref=customer,
                product_ref=product,
                payment_ref=payment,
                amount_minor=amount,
                currency=currency,
                occurred_at=_when(data.get("created")),
                raw_type=raw_type[:100],
            )
        ]

    def _verify(self, headers: Mapping[str, str], body: bytes) -> None:
        header = headers.get(SIGNATURE_HEADER)
        if not header:
            raise InvalidSignature
        stamp: int | None = None
        candidates: list[str] = []
        for part in header.split(","):
            key, sep, value = part.strip().partition("=")
            if not sep:
                continue
            if key == "t":
                try:
                    stamp = int(value)
                except ValueError:
                    raise InvalidSignature from None
            elif key == "v1":  # every other scheme (Stripe's fake `v0` on test events) is ignored: no downgrade
                candidates.append(value)
        if stamp is None or not candidates:
            raise InvalidSignature
        expected = self._mac(stamp, body)
        # Constant-time against EVERY v1 (a rolled secret sends one per active secret), accumulated without short-circuiting, and the
        # MAC is checked BEFORE the window, so a wrong signature and a stale one are indistinguishable from outside.
        matched = False
        for candidate in candidates:
            matched |= hmac.compare_digest(candidate.encode(), expected.encode())
        if not matched or self._clock() - stamp > self._tolerance:
            raise InvalidSignature

    def _mac(self, stamp: int, body: bytes) -> str:
        return hmac.new(self._secret, f"{stamp}.".encode() + body, hashlib.sha256).hexdigest()

    # --- checkout, outbound -----------------------------------------------------------------------------

    async def create_checkout(
        self, customer: BillingCustomer, product: CreditProduct, *, idempotency_key: str, success_url: str, cancel_url: str
    ) -> CheckoutSession:
        """A hosted Checkout Session for ONE unit of the pack's Stripe price, for Stripe customer `customer.customer_ref`.

        `idempotency_key` is sent as Stripe's `Idempotency-Key`, so a retry of the same purchase attempt returns the SAME session
        (and a different attempt must use a different key). The tenant is deliberately not sent: Stripe knows its own customer id,
        and the link from that id to a tenant is this app's table, not Stripe's metadata."""
        if not self._api_key:
            raise CheckoutError("STRIPE_API_KEY is not set", retryable=False, code="no_api_key")
        if not idempotency_key or len(idempotency_key) > 255:
            raise CheckoutError("an idempotency key is 1 to 255 characters", retryable=False, code="bad_idempotency_key")
        form = {
            "mode": "payment",
            "line_items[0][price]": product.product_ref,
            "line_items[0][quantity]": "1",
            "customer": customer.customer_ref,
            "success_url": success_url,
            "cancel_url": cancel_url,
            "metadata[product_ref]": product.product_ref,  # what checkout.session.completed will echo back
        }
        headers = {"Authorization": f"Bearer {self._api_key}", "Idempotency-Key": idempotency_key}
        try:
            async with httpx.AsyncClient(base_url=self._api_base, timeout=REQUEST_TIMEOUT_SECONDS, transport=self._transport) as client:
                response = await client.post("/v1/checkout/sessions", data=form, headers=headers)
        except httpx.HTTPError as exc:
            raise CheckoutError(f"could not reach Stripe ({type(exc).__name__})", retryable=True, code="network") from exc
        if response.status_code != 200:
            raise _checkout_error(response)
        try:
            body = response.json()
            session_ref, url = body["id"], body["url"]
        except (ValueError, KeyError, TypeError):
            raise CheckoutError("Stripe answered 200 with no session", retryable=False, status=200, code="bad_response") from None
        if not isinstance(session_ref, str) or not isinstance(url, str) or not session_ref or not url:
            raise CheckoutError("Stripe answered 200 with no session", retryable=False, status=200, code="bad_response")
        return CheckoutSession(session_ref=session_ref, url=url)

    # --- capabilities this adapter does not declare (D16) ------------------------------------------------

    async def export_usage(self, customer: BillingCustomer, events: Sequence[UsageEvent]) -> ExportResult:
        raise NotImplementedError("the stripe adapter declares no USAGE_EXPORT capability (spec D16: prepaid packs)")

    async def read_balance(self, *args, **kwargs):
        raise NotImplementedError("the stripe adapter declares no BALANCE_READ capability")


def _normalize(raw_type: str, obj: Mapping[str, Any]) -> tuple[EventKind, str | None, str | None, str | None, int | None, str | None]:
    """(kind, customer, product, payment, amount_minor, currency) for one event. Only the fields the app needs are read: a Stripe
    object has hundreds, and buyer details among them must never be reached for."""
    currency = _text(obj.get("currency"))
    if raw_type in _PAID:
        # One-time packs only (D16), and only once PAID: a delayed payment method completes the session UNPAID and Stripe sends
        # `async_payment_succeeded` later, which is the event that grants.
        if obj.get("mode") != "payment" or obj.get("payment_status") != "paid":
            return EventKind.IGNORED, None, None, None, None, None
        metadata = obj.get("metadata")
        product = _text(metadata.get("product_ref")) if isinstance(metadata, dict) else None
        return EventKind.CREDITS_PURCHASED, _id(obj.get("customer")), product, _id(obj.get("payment_intent")), _int(obj.get("amount_total")), currency
    if raw_type == "charge.refunded":
        # `refunded` is true only for a FULL refund; the event also fires for a partial one (docs: "including partial refunds").
        kind = EventKind.PAYMENT_REFUNDED if obj.get("refunded") is True else EventKind.PAYMENT_PARTIALLY_REFUNDED
        return kind, _id(obj.get("customer")), None, _id(obj.get("payment_intent")), _int(obj.get("amount_refunded")), currency
    if raw_type in ("charge.dispute.created", "charge.dispute.closed"):
        kind = EventKind.DISPUTE_OPENED if raw_type.endswith("created") else EventKind.DISPUTE_CLOSED
        return kind, None, None, _id(obj.get("payment_intent")), _int(obj.get("amount")), currency  # a Dispute has no `customer`
    return EventKind.IGNORED, None, None, None, None, None


def _checkout_error(response: httpx.Response) -> CheckoutError:
    """By status, error type, code and the NAME of the offending field: Stripe's `message` can quote a key fragment or a URL."""
    kind = code = param = None
    try:
        error = response.json().get("error") or {}
        kind, code, param = _text(error.get("type")), _text(error.get("code")), _text(error.get("param"))
    except (ValueError, AttributeError):
        pass
    if param is not None and not _PARAM.fullmatch(param):
        param = None
    status = response.status_code
    # 409 is a request for this key still executing, 429 a rate limit, 5xx Stripe's own trouble: all worth trying again with the
    # SAME key. Any other 4xx is the request being wrong, and trying again will say the same (Stripe replays the first result).
    retryable = status in (409, 429) or status >= 500
    detail = (
        f"Stripe refused the checkout (HTTP {status}" + (f", {kind}" if kind else "") + (f", {code}" if code else "")
        + (f", field {param}" if param else "") + "); the reason is in the Stripe Dashboard's request logs"
    )
    return CheckoutError(detail, retryable=retryable, status=status, code=code or kind)


def _text(value: Any) -> str | None:
    return value if isinstance(value, str) and value else None


def _id(value: Any) -> str | None:
    """A Stripe reference is a string id; an EXPANDED one is an object carrying it. Webhooks send ids, but accept both."""
    if isinstance(value, dict):
        value = value.get("id")
    return _text(value)


def _int(value: Any) -> int | None:
    return value if isinstance(value, int) and not isinstance(value, bool) else None


def _when(value: Any) -> datetime | None:
    try:
        return datetime.fromtimestamp(int(value), UTC) if value is not None else None
    except (TypeError, ValueError, OverflowError, OSError):
        return None
